// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI1PUqbden-qaSW7QGCwOslPZbDfuoU6c',
    appId: '1:25436279027:web:6946660b53abe7e285e786',
    messagingSenderId: '25436279027',
    projectId: 'ap-assignment-financial',
    authDomain: 'ap-assignment-financial.firebaseapp.com',
    storageBucket: 'ap-assignment-financial.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcTFgWdf1__J4g7Az4OSKl40Y9X4vSP6M',
    appId: '1:25436279027:android:bb08551208a687e585e786',
    messagingSenderId: '25436279027',
    projectId: 'ap-assignment-financial',
    storageBucket: 'ap-assignment-financial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCELQ5CuayMgNTyhDIBPiUo6_KiE5Dc5e8',
    appId: '1:25436279027:ios:f9de45dc686c091d85e786',
    messagingSenderId: '25436279027',
    projectId: 'ap-assignment-financial',
    storageBucket: 'ap-assignment-financial.appspot.com',
    iosBundleId: 'com.example.financialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCELQ5CuayMgNTyhDIBPiUo6_KiE5Dc5e8',
    appId: '1:25436279027:ios:10c0934e7650f7fc85e786',
    messagingSenderId: '25436279027',
    projectId: 'ap-assignment-financial',
    storageBucket: 'ap-assignment-financial.appspot.com',
    iosBundleId: 'com.example.financialApp.RunnerTests',
  );
}
